<?xml version="1.0" encoding="iso-8859-1"?>
<!--<!DOCTYPE NEWSPAPER SYSTEM "news.dtd">-->
<!DOCTYPE NEWSPAPER [
        <!ELEMENT NEWSPAPER (ARTICLE+)>
        <!ELEMENT ARTICLE (HEADLINE,BYLINE,LEAD,BODY,NOTES)>
        <!ELEMENT HEADLINE (#PCDATA)>
        <!ELEMENT BYLINE (#PCDATA)>
        <!ELEMENT LEAD (#PCDATA)>
        <!ELEMENT BODY (#PCDATA)>
        <!ELEMENT NOTES (#PCDATA)>

        <!ATTLIST ARTICLE AUTHOR CDATA #REQUIRED>
        <!ATTLIST ARTICLE EDITOR CDATA #IMPLIED>
        <!ATTLIST ARTICLE DATE CDATA #IMPLIED>
        <!ATTLIST ARTICLE EDITION CDATA #IMPLIED>

        <!ENTITY NEWSPAPER "Vervet Logic Times">
        <!ENTITY PUBLISHER "Vervet Logic Press">
        <!ENTITY COPYRIGHT "Copyright 1998 Vervet Logic Press">
]>
<NEWSPAPER>
    <ARTICLE AUTHOR="&NEWSPAPER;" EDITOR="implied" DATE="implied" DIETION="implied">
        <HEADLINE>&NEWSPAPER;</HEADLINE>
        <BYLINE>&PUBLISHER;</BYLINE>
        <LEAD>&COPYRIGHT;</LEAD>
        <BODY>xxx</BODY>
        <NOTES>eeee</NOTES>
    </ARTICLE>
</NEWSPAPER>