<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE TVSCHEDULE SYSTEM "tv.dtd">
<!--<!DOCTYPE TVSCHEDULE [
        <!ELEMENT TVSCHEDULE (CHANNEL+)>
        <!ELEMENT CHANNEL (BANNER,DAY+)>
        <!ELEMENT BANNER (#PCDATA)>
        <!ELEMENT DAY (DATE,(HOLIDAY|PROGRAMSLOT)+)>
        <!ELEMENT HOLIDAY (#PCDATA)>
        <!ELEMENT DATE (#PCDATA)>
        <!ELEMENT PROGRAMSLOT (TIME,TITLE,DESCRIPTION?)>
        <!ELEMENT TIME (#PCDATA)>
        <!ELEMENT TITLE (#PCDATA)>
        <!ELEMENT DESCRIPTION (#PCDATA)>

        <!ATTLIST TVSCHEDULE NAME CDATA #REQUIRED>
        <!ATTLIST CHANNEL CHAN CDATA #REQUIRED>
        <!ATTLIST PROGRAMSLOT VTR CDATA #IMPLIED>
        <!ATTLIST TITLE RATING CDATA #IMPLIED>
        <!ATTLIST TITLE LANGUAGE CDATA #IMPLIED>
        ]>-->
<TVSCHEDULE NAME="CCTV12">
    <CHANNEL CHAN="12">
        <BANNER>banner</BANNER>
        <DAY>
            <DATE>33</DATE>
            <HOLIDAY>dd</HOLIDAY>
            <HOLIDAY>dd</HOLIDAY>
            <HOLIDAY>dd</HOLIDAY>
            <HOLIDAY>dd</HOLIDAY>
            <HOLIDAY>dd</HOLIDAY>

            <PROGRAMSLOT>
                <TIME>ee</TIME>
                <TITLE>ss</TITLE>
            </PROGRAMSLOT>
            <PROGRAMSLOT>
                <TIME>xx</TIME>
                <TITLE>ee</TITLE>
            </PROGRAMSLOT>
        </DAY>

        <DAY>
            <DATE>44</DATE>
            <HOLIDAY>xx</HOLIDAY>
        </DAY>
    </CHANNEL>
</TVSCHEDULE>